# ./docker-compose.yml 
version: "3.9"

services:
  app:
    build: . #this is the root dir, this path is where server.js needs to be. 
    container_name: health_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-app_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-app_pass}
      DB_NAME: ${MYSQL_DATABASE:-fitnessbuddy}
      SESSION_SECRET: ${SESSION_SECRET:-change_this}
    depends_on:
      - mariadb
    networks:
      - healthnet

  mariadb:
    image: mariadb:11
    container_name: health_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fitnessbuddy}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_pass}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    networks:
      - healthnet

networks:
  healthnet:

volumes:
  mariadb_data:
